### PR TITLE
WIP: Show linenumbers

### PR DESCRIPTION
**Pull request by eval**
This PR ensures that the origin of a log-statement (`ns:line`) is shown:

```
 [  0.226s] [foo.core:51] [DEBUG] some debug
 [  0.227s] [foo.main:34] [ERROR] some error
```

While just appending another block would have been an option (eg `[  0.227s] [foo.main] [ERROR] [foo.main:34] some error`). This would take up quite some space and would've (the logger-name being the namespace) duplicate information.  
Instead the logger-name was disabled and the `ns:line` prepended to the message.

(ignore changes to `deps.edn` - this is for testing purpose).  

Is this something to workout?

Tasks:
- [x] fix test
- [x] reflect new format in README
- [x] test in browser (currently tested with node)
- [x] remove deps.edn

Test via demo-branch:
```bash
# browser
$ clj -Sdeps "{:deps {otarta {:git/url \"git@github.com:eval/huon.git\" :sha \"dd26792114d2a12e715d488a15d2509c78553e15\"}}}}" -m cljs.main -e '(require (quote [huon.log :as log]))' --repl
cljs.user=> (log/error "some error")
;; shows "log:[cljs.user:1] [ERROR] some error" in browser's console

# node
$ clj -Sdeps "{:deps {otarta {:git/url \"git@github.com:eval/huon.git\" :sha \"dd26792114d2a12e715d488a15d2509c78553e15\"}}}}" -m cljs.main -re node -e '(require (quote [huon.log :as log]))(log/enable!)' --repl
cljs.user=> (log/info "some error")
 [  8.767s] [cljs.user:1] [INFO] some error
nil
```

### CODE REVIEW

**Comment by harto** [comment]
Thanks, this looks like a nice improvement!

**Comment by eval** [comment]
@harto I wrapped it up. Feedback welcome!

**Comment by harto** [comment]
Looks great. Thank you!

**Comment by harto** [comment]
Released as 0.5.0.

**Pull request merged**
